server:
  port: 8080

spring:
  application:
    name: gateway-server

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: gateway-server
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
